spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon  # ?????? URL (MySQL ??)
    username: root  # ?????? ????
    password: password123  # ?????? ????
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL ???? ???

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 ?? ??, ??? ?? ?? ??
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200